controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

root_route_config:
    path: /
    controller: App\Controller\CompanyController::new
